---
jobs:
  changelog:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - name: "Conventional Changelog Action"
        id: "changelog"
        uses: "TriPSs/conventional-changelog-action@v3"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          release-count: "0"

name: "Changelog"

"on":
  push:
    branches:
      - "main"
